apiVersion: v1
kind: pod
metadata:
  name: private-image-test-1

spec:
  containers:
    - name: dashapp
      image: dtr.k8s.co/kismatic/oracle-java7
      command: [ "echo", "SUCCESS" ]
  imagePullSecrets:
    - name: dockerkey1
        